" Enable line numbers
set number

" Highlight search results
set hlsearch

" Enable mouse support
set mouse=a

" Show Matching parentheses
set showmatch

" incremental search
set incsearch

" converts tabs into white spaces
set expandtab

" width for autoindents
set shiftwidth=4

" number of columns occupied by a tab
set tabstop=4

" see multiple spaces as tabstops so <BS> does the right thing
set softtabstop=4

" indent a new line the same amount as the line just typed
set autoindent

" set an 80 column border for good coding style
set cc=80

" syntax highlighting
syntax on 

" Idk tbh but it's good to have
set relativenumber 

if v:version < 802 
    packadd! dracula 
endif 

syntax enable 
colorscheme dracula
